#!/usr/bin/env bash
# run.sh — Wrapper that runs pi-slack-bot with auto-restart support.
#
# The bot exits with code 75 to request a restart (e.g., via !restart command).
# Any other exit code stops the loop.
#
# NODE_PATH: The pi SDK resolves installed pi packages (providers, extensions,
# skills) via NODE_PATH. The `pi` CLI launcher (pnpm shim) sets this automatically,
# but when running the bot directly (e.g., via systemd), NODE_PATH must be sourced
# from the pi launcher. Without it, providers like kiro won't be found.
#
# Usage:
#   ./run.sh              # run in foreground
#   tmux new -d -s bot './run.sh'   # run in tmux

set -euo pipefail
cd "$(dirname "$0")"

# Source NODE_PATH from the pi launcher so the SDK can resolve installed pi packages
# (providers, extensions, skills). The pi shim is generated by pnpm and sets NODE_PATH.
# NOTE: This parses the pnpm-generated shim format, which is an implementation detail.
# If pnpm changes the shim format, this extraction may need updating.
# Alternative: `pnpm root -g` gives the global modules path but not the full
# three-path NODE_PATH that pi's internal resolution requires.
PI_BIN="$(command -v pi 2>/dev/null || echo "$HOME/.local/share/pnpm/pi")"
if [ -f "$PI_BIN" ]; then
  # Extract the quoted NODE_PATH value from the shim without eval
  NODE_PATH_VALUE=$(grep 'export NODE_PATH=' "$PI_BIN" 2>/dev/null | head -1 | sed -n 's/.*export NODE_PATH="\([^"]*\)".*/\1/p' || true)
  if [ -n "$NODE_PATH_VALUE" ]; then
    export NODE_PATH="$NODE_PATH_VALUE${NODE_PATH:+:$NODE_PATH}"
  fi
fi

if [ -z "${NODE_PATH:-}" ]; then
  echo "[run.sh] WARNING: NODE_PATH not set — pi packages (providers, extensions) may not be found" >&2
fi

# Node heap sizing: Node 22 auto-sizes --max-old-space-size from the cgroup memory limit
# (roughly half of MemoryMax). Under a 1G systemd MemoryMax this lands at ~380 MB, which
# is too small for multiple active sessions. Set a sane floor unless the caller overrides.
: "${NODE_OPTIONS:=--max-old-space-size=768}"
export NODE_OPTIONS

RESTART_EXIT_CODE=75
RESTART_DELAY=2  # seconds between restart cycles

while true; do
  echo "[run.sh] Starting pi-slack-bot..."
  set +e
  node --import tsx/esm src/index.ts
  exit_code=$?
  set -e

  if [ "$exit_code" -eq "$RESTART_EXIT_CODE" ]; then
    echo "[run.sh] Bot requested restart (exit $RESTART_EXIT_CODE). Restarting in ${RESTART_DELAY}s..."
    sleep "$RESTART_DELAY"
    continue
  fi

  echo "[run.sh] Bot exited with code $exit_code. Stopping."
  exit "$exit_code"
done
